#!/bin/sh

if [[ $EUID -ne 0 ]]; then
   echo "This command need to be run as root."
   echo "Try 'sudo $0 $*'"
   exit 1
fi

exec docker run -v /tmp/pbg:/pbg -p 127.0.0.1:8888:8888 registry.lrde.epita.fr/mooc-pysci3
